name: Workflow jobs
on:
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Myfirst job
        run: |
          echo "Myfirst job is success"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: MySecound_job
        run: |
          echo "If my first is success run only then my secound job will br run"
    job3:
      runs-on: ubuntu-latest
      needs: [job1, job2]
      steps:
        - name: My_ThirdJob
          run: |
            echo "job1 and job2 success execute then on job3 will run"